export const students = [
  {
    id: 1,
    name: "User 1",
    contributions: 5000,
    university: "Harvard University",
    avatar: "https://avatars.githubusercontent.com/u/86526696?v=4",
  },
  {
    id: 2,
    name: "User 2",
    contributions: 4500,
    university: "Stanford University",
    avatar: "https://avatars.githubusercontent.com/u/86526696?v=4",
  },
  {
    id: 3,
    name: "User 3",
    contributions: 4000,
    university: "MIT",
    avatar: "https://avatars.githubusercontent.com/u/86526696?v=4",
  },
  {
    id: 4,
    name: "User 4",
    contributions: 3500,
    university: "University of California, Berkeley",
    avatar: "https://avatars.githubusercontent.com/u/86526696?v=4",
  },
  {
    id: 5,
    name: "User 5",
    contributions: 3000,
    university: "University of Oxford",
    avatar: "https://avatars.githubusercontent.com/u/86526696?v=4",
  },
  {
    id: 6,
    name: "User 6",
    contributions: 2500,
    university: "University of Cambridge",
    avatar: "https://avatars.githubusercontent.com/u/86526696?v=4",
  },
  {
    id: 7,
    name: "User 7",
    contributions: 2000,
    university: "California Institute of Technology",
    avatar: "https://avatars.githubusercontent.com/u/86526696?v=4",
  },
  {
    id: 8,
    name: "User 8",
    contributions: 1500,
    university: "Princeton University",
    avatar: "https://avatars.githubusercontent.com/u/86526696?v=4",
  },
  {
    id: 9,
    name: "User 9",
    contributions: 1000,
    university: "Yale University",
    avatar: "https://avatars.githubusercontent.com/u/86526696?v=4",
  },
  {
    id: 10,
    name: "User 10",
    contributions: 500,
    university: "Columbia University",
    avatar: "https://avatars.githubusercontent.com/u/86526696?v=4",
  },
];
